# Generated by Django 4.0.2 on 2023-02-03 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_billing_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='expire_date',
            field=models.DateField(default=datetime.date(2023, 3, 5)),
        ),
        migrations.AlterField(
            model_name='billing',
            name='reference_code',
            field=models.TextField(default='n45xt5l416t5x5r1cqc5'),
        ),
    ]
