# Generated by Django 4.0.2 on 2022-04-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='join',
            options={'verbose_name_plural': 'Join'},
        ),
        migrations.AlterModelOptions(
            name='polar',
            options={'verbose_name_plural': 'Polar'},
        ),
    ]
