# Generated by Django 4.0.2 on 2023-02-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0002_alter_join_options_alter_polar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traverse_name', models.CharField(max_length=250)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('distance', models.TextField()),
                ('angle', models.TextField()),
                ('end_lat', models.FloatField()),
                ('end_lon', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Traversing',
            },
        ),
    ]
