# Generated by Django 5.1.4 on 2025-01-12 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0003_traverse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('initial_rl', models.DecimalField(decimal_places=3, max_digits=10)),
                ('final_rl', models.DecimalField(decimal_places=3, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LevelingReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
                ('bs', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_sight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fs', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rise', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fall', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rl', models.DecimalField(decimal_places=3, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('reading_order', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='computation.levelingproject')),
            ],
            options={
                'ordering': ['reading_order'],
            },
        ),
    ]
