# Generated by Django 4.0.2 on 2022-04-11 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRS',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Coordinate Reference Systems',
            },
        ),
        migrations.CreateModel(
            name='CoordinateTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='X/Lon')),
                ('y', models.FloatField(verbose_name='Y/Lat')),
                ('x_trans', models.FloatField(blank=True, null=True, verbose_name='X-Transformed')),
                ('y_trans', models.FloatField(blank=True, null=True, verbose_name='Y-Transformed')),
                ('stored_on', models.DateTimeField(auto_now_add=True)),
                ('from_epsg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_epsg', to='coordinate_conversion.crs')),
                ('to_epsg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_epsg', to='coordinate_conversion.crs')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Coordinate Conversions',
            },
        ),
    ]
