# Generated by Django 4.0.2 on 2022-04-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate_conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatetransform',
            name='from_epsg',
            field=models.CharField(choices=[('4326', 'WGS84'), ('20936', 'Arc1950')], max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinatetransform',
            name='to_epsg',
            field=models.CharField(choices=[('4326', 'WGS84'), ('20936', 'Arc1950')], max_length=100),
        ),
        migrations.DeleteModel(
            name='CRS',
        ),
    ]
