# Generated by Django 4.0.2 on 2022-04-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate_conversion', '0002_alter_coordinatetransform_from_epsg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatetransform',
            name='from_epsg',
            field=models.CharField(choices=[('4326', 'EPSG:4326 WGS 84'), ('3857', 'EPSG:3857 WGS 84 / Pseudo-Mercator'), ('4209', 'EPSG:4209 Arc 1950'), ('20935', 'EPSG: 20935 Arc 1950 / UTM zone 35S'), ('20936', 'EPSG: 20936  Arc 1950 / UTM zone 36S '), ('32735', 'EPSG: 32735 WGS 84 / UTM zone 35S'), ('32736', 'EPSG: 32736 WGS 84 / UTM zone 36S'), ('9378', 'EPSG: 9378 IGb14'), ('7789', 'EPSG: 7789 ITRF2014'), ('4979', 'EPSG: 4979 WGS 84'), ('2054', 'EPSG: 2054 Hartebeesthoek94 / Lo31')], max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinatetransform',
            name='to_epsg',
            field=models.CharField(choices=[('4326', 'EPSG:4326 WGS 84'), ('3857', 'EPSG:3857 WGS 84 / Pseudo-Mercator'), ('4209', 'EPSG:4209 Arc 1950'), ('20935', 'EPSG: 20935 Arc 1950 / UTM zone 35S'), ('20936', 'EPSG: 20936  Arc 1950 / UTM zone 36S '), ('32735', 'EPSG: 32735 WGS 84 / UTM zone 35S'), ('32736', 'EPSG: 32736 WGS 84 / UTM zone 36S'), ('9378', 'EPSG: 9378 IGb14'), ('7789', 'EPSG: 7789 ITRF2014'), ('4979', 'EPSG: 4979 WGS 84'), ('2054', 'EPSG: 2054 Hartebeesthoek94 / Lo31')], max_length=100),
        ),
    ]
