# Generated by Django 4.0.2 on 2022-04-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlNetworkPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonuNum', models.CharField(blank=True, max_length=50, null=True)),
                ('Run_no', models.CharField(blank=True, max_length=50, null=True)),
                ('MonuNm', models.CharField(blank=True, max_length=50, null=True)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Comp_sheet', models.CharField(blank=True, max_length=50, null=True)),
                ('TOPO', models.CharField(blank=True, max_length=50, null=True)),
                ('Gauss_Lo', models.CharField(blank=True, max_length=50, null=True)),
                ('LO', models.CharField(blank=True, max_length=50, null=True)),
                ('Y_Gauss', models.CharField(blank=True, max_length=50, null=True)),
                ('Y_LO', models.CharField(blank=True, max_length=50, null=True)),
                ('X_Gauss', models.CharField(blank=True, max_length=50, null=True)),
                ('X_LO', models.CharField(blank=True, max_length=50, null=True)),
                ('MSL_Hgt', models.CharField(blank=True, max_length=50, null=True)),
                ('H_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('LatCD', models.CharField(blank=True, max_length=50, null=True)),
                ('LonCD', models.CharField(blank=True, max_length=50, null=True)),
                ('P_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('CM_UTM', models.CharField(blank=True, max_length=50, null=True)),
                ('UTMCM', models.CharField(blank=True, max_length=50, null=True)),
                ('E_UTM', models.CharField(blank=True, max_length=50, null=True)),
                ('Y_UTM', models.CharField(blank=True, max_length=50, null=True)),
                ('N_UTM', models.CharField(blank=True, max_length=50, null=True)),
                ('X_UTM', models.CharField(blank=True, max_length=50, null=True)),
                ('Lat_WGS84', models.CharField(blank=True, max_length=50, null=True)),
                ('Lon_WGS84', models.CharField(blank=True, max_length=50, null=True)),
                ('P84_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('EllpHgt', models.CharField(blank=True, max_length=50, null=True)),
                ('H84_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('Geoid_Sep', models.CharField(blank=True, max_length=50, null=True)),
                ('Src_Geoid', models.CharField(blank=True, max_length=50, null=True)),
                ('PedHgt', models.CharField(blank=True, max_length=50, null=True)),
                ('PillHgt', models.CharField(blank=True, max_length=50, null=True)),
                ('TopSignal', models.CharField(blank=True, max_length=50, null=True)),
                ('BotSignal', models.CharField(blank=True, max_length=50, null=True)),
                ('Establ', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_Revisions', models.CharField(blank=True, max_length=50, null=True)),
                ('Observed', models.CharField(blank=True, max_length=50, null=True)),
                ('Computed', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_insp', models.CharField(blank=True, max_length=50, null=True)),
                ('Destroy', models.CharField(blank=True, max_length=50, null=True)),
                ('DegSqr', models.CharField(blank=True, max_length=50, null=True)),
                ('Invest', models.CharField(blank=True, max_length=50, null=True)),
                ('Check', models.CharField(blank=True, max_length=50, null=True)),
                ('Remark', models.CharField(blank=True, max_length=50, null=True)),
                ('Intervisibility', models.CharField(blank=True, max_length=50, null=True)),
                ('AREA_NM', models.CharField(blank=True, max_length=50, null=True)),
                ('Township', models.CharField(blank=True, max_length=50, null=True)),
                ('Reported_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Geodetic Control Network',
            },
        ),
    ]
