# Generated by Django 4.0.2 on 2022-04-05 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0007_reversegeocode_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reversegeocode',
            options={'verbose_name_plural': 'Reverse'},
        ),
        migrations.AlterModelOptions(
            name='singleaddressgeocode',
            options={'verbose_name_plural': 'Single-Address'},
        ),
        migrations.AddField(
            model_name='reversegeocode',
            name='meta_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleaddressgeocode',
            name='meta_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
