# Generated by Django 4.0.2 on 2022-05-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
    ]
