# Generated by Django 4.0.2 on 2022-03-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('priority_level', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
